gems:
  - jekyll-seo-tag

# Setup
title:            Simple IP Config
tagline:          'IP addresses'
description:      'view and change your local IP addresses'
url:              https://kurtisliggett.github.io
baseurl:         ""

author:
  name:           'Kurtis Liggett'
  url:            https://kurtisliggett.github.io

paginate:         5

# Custom vars
version:          2.8
project:        Simple-IP-Config
repository:     'KurtisLiggett/Simple-IP-Config'


github:
  repo:           https://github.com/KurtisLiggett/Simple-IP-Config
